### ISSUE TITLE
getClans() Bug

### ISSUE THREAD

**Issue by Samiul30** [clashperk/clashofclans.js#143]
### Bug while searching clans using getClans() method.

Expected results: It should return all the clans with the search parameters.

real behaviour: 
`E:\My Work\Discord Bots\Game One\node_modules\clashofclans.js\dist\struct\Clan.js:37
        this.clanCapital = Object.keys(data.clanCapital).length > 0 ? new ClanCapital_1.ClanCapital(data.clanCapital) : null;
                                  ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at new Clan (E:\My Work\Discord Bots\Game One\node_modules\clashofclans.js\dist\struct\Clan.js:37:35)
    at E:\My Work\Discord Bots\Game One\node_modules\clashofclans.js\dist\client\Client.js:59:41
    at Array.map (<anonymous>)
    at Client.getClans (E:\My Work\Discord Bots\Game One\node_modules\clashofclans.js\dist\client\Client.js:59:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async E:\My Work\Discord Bots\Game One\tools\coc.js:6:18
   `

**Comment by csuvajit** [comment]
it has been fixed.
